# Generated by Django 3.2.3 on 2022-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmap',
            name='genre1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sessionmap',
            name='genre2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
