# Generated by Django 3.1.6 on 2021-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20210426_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmap',
            name='genre1',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Electronic'), ('ROCK', 'Rock'), ('ALT', 'Alternative'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('RAP', 'Rap'), ('HH', 'Hip-hop'), ('AMBIENT', 'Ambient'), ('TECHNO', 'Techno'), ('DUBSTEP', 'Dubstep'), ('DNB', 'Drum & Bass'), ('POP', 'Pop'), ('FOLK', 'Folk'), ('PSYCH', 'Psychedelic'), ('LOFI', 'Lo-Fi'), ('NOISE', 'Noise'), ('HARDCORE', 'Hardcore'), ('DARK', 'Dark'), ('INSTRUMENTAL', 'Instrumental'), ('INDIE', 'Indie'), ('EXP', 'Experimental'), ('HOUSE', 'House'), ('TRANCE', 'Trance'), ('ACOUSTICE', 'Acoustice'), ('NONE', 'None')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre2',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Electronic'), ('ROCK', 'Rock'), ('ALT', 'Alternative'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('RAP', 'Rap'), ('HH', 'Hip-hop'), ('AMBIENT', 'Ambient'), ('TECHNO', 'Techno'), ('DUBSTEP', 'Dubstep'), ('DNB', 'Drum & Bass'), ('POP', 'Pop'), ('FOLK', 'Folk'), ('PSYCH', 'Psychedelic'), ('LOFI', 'Lo-Fi'), ('NOISE', 'Noise'), ('HARDCORE', 'Hardcore'), ('DARK', 'Dark'), ('INSTRUMENTAL', 'Instrumental'), ('INDIE', 'Indie'), ('EXP', 'Experimental'), ('HOUSE', 'House'), ('TRANCE', 'Trance'), ('ACOUSTICE', 'Acoustice'), ('NONE', 'None')], max_length=15, null=True),
        ),
    ]
