# Generated by Django 3.1.6 on 2021-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20210426_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmap',
            options={'ordering': ['genre1', 'genre2']},
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre1',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Electronic'), ('ROCK', 'Rock'), ('ALTERNATIVE', 'Alternative'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('RAP', 'Rap'), ('HIP-HOP', 'Hip-hop'), ('AMBIENT', 'Ambient'), ('TECHNO', 'Techno'), ('DUBSTEP', 'Dubstep'), ('DRUM N BASS', 'Drum n Bass'), ('POP', 'Pop'), ('FUTURE', 'Future'), ('DIY', 'DIY'), ('STONER', 'Stoner'), ('ACID', 'Acid'), ('DOWNTEMPO', 'Downtempo'), ('DEEP', 'Deep'), ('CONTEMPORARY', 'Contemporary'), ('FOLK', 'Folk'), ('PSYCH', 'Psychedelic'), ('JUNGLE', 'Jungle'), ('LOFI', 'Lo-Fi'), ('NOISE', 'Noise'), ('HARDCORE', 'Hardcore'), ('DARK', 'Dark'), ('INSTRUMENTAL', 'Instrumental'), ('INDIE', 'Indie'), ('EXP', 'Experimental'), ('HOUSE', 'House'), ('TRANCE', 'Trance'), ('ACOUSTIC', 'Acoustic'), ('JUKE', 'Juke'), ('FOOTWORK', 'Footwork')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre2',
            field=models.CharField(blank=True, choices=[('ELECTRONIC', 'Electronic'), ('ROCK', 'Rock'), ('ALTERNATIVE', 'Alternative'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('RAP', 'Rap'), ('HIP-HOP', 'Hip-hop'), ('AMBIENT', 'Ambient'), ('TECHNO', 'Techno'), ('DUBSTEP', 'Dubstep'), ('DRUM N BASS', 'Drum n Bass'), ('POP', 'Pop'), ('FUTURE', 'Future'), ('DIY', 'DIY'), ('STONER', 'Stoner'), ('ACID', 'Acid'), ('DOWNTEMPO', 'Downtempo'), ('DEEP', 'Deep'), ('CONTEMPORARY', 'Contemporary'), ('FOLK', 'Folk'), ('PSYCH', 'Psychedelic'), ('JUNGLE', 'Jungle'), ('LOFI', 'Lo-Fi'), ('NOISE', 'Noise'), ('HARDCORE', 'Hardcore'), ('DARK', 'Dark'), ('INSTRUMENTAL', 'Instrumental'), ('INDIE', 'Indie'), ('EXP', 'Experimental'), ('HOUSE', 'House'), ('TRANCE', 'Trance'), ('ACOUSTIC', 'Acoustic'), ('JUKE', 'Juke'), ('FOOTWORK', 'Footwork')], max_length=15, null=True),
        ),
    ]
