# Generated by Django 3.1.6 on 2021-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20210521_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmap',
            options={},
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
