# Generated by Django 3.1.6 on 2021-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20210609_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmap',
            name='mode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
