# Generated by Django 3.1.6 on 2022-07-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_sessionmap_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmap',
            name='mode',
        ),
    ]
