# Generated by Django 3.2.3 on 2022-07-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20210427_2157'),
        ('frontpage', '0007_remove_sessionmap_mode'),
    ]

    operations = [
    ]
