# Generated by Django 3.2.3 on 2022-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_merge_20220720_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmap',
            name='genre1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sessionmap',
            name='genre2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
